---
title: "map_Korean_covid19_testing_center"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
    theme: flatly
---

```{r setup, include=FALSE}
Sys.setlocale("LC_ALL", "Korean")
library(readr)
library(flexdashboard)
library(shiny)
library(leaflet)
library(dplyr)

```

```{r}

urlfile= "https://raw.githubusercontent.com/Yunjeong-Kim/covid19_south_korea/master/korea_testing_center.csv"
korean <- read_csv(url(urlfile), locale = locale(date_names = "he", encoding = "UTF-8"))

#define sigungu
korean$singungu <- as.factor(korean$singungu)
korean$sido <- as.factor(korean$sido)
sidoname <- levels(korean$sido)
#singunguname <- levels(korean$singungu)
```

Test Centers
======================================================================

Input {.sidebar}
-----------------------------------------------------------------------

### Select your area

```{r}
        
# define inputs
library(dplyr)
selectInput("sido", label = "City or Province", choices = sidoname)

  selectedSido <- list(reactive(as.factor(input$sido)))
  selectedData = korean %>%
    select(singungu) %>%
    filter(korean$sido==selectedSido)
  singunguname <- levels(selectedData$singungu)
  
selectInput("sigungu", label = "County", choices = singunguname)
        
```

Column {data-width=2500}
-----------------------------------------------------------------------

### COVID19 Test Center in your Selected Area

```{r}
# filter the data to the selected region/district

filtereddata <- reactive({
        filter(korean, sido == input$sido)
        }
        )
# Draw the map that shows the testing center
renderLeaflet({
        leaflet(filtereddata()) %>%
        addProviderTiles("CartoDB.Positron") %>%
       addMarkers(lng = ~lon, lat = ~lat, popup = ~telephone)
  
})

# click event(testing center) for the map
# will generate detailed infor of the testing center

click_tract <- eventReactive(input$map_tile_click,{
        
}
                             
)
```

Statistics
======================================================================

Column {data-width=200}
-----------------------------------------------------------------------

### Side Bar

```{r}

library(plotly)
library(ggplot2)
library(tidyverse)
urlfile2= "https://raw.githubusercontent.com/Yunjeong-Kim/covid19_south_korea/master/daily_total.csv"
dat <- read_csv(url(urlfile2))

covid19 <- data.frame(t(dat[-1]))
colnames(covid19)[1:5] <- c("test", "negative", "confirmed", "released", "death")
covid19<-tibble::rownames_to_column(covid19, "date") 

covid19 <- covid19 %>%
  mutate(cumconfirmed = cumsum(confirmed)) %>%
  mutate(cumdeath = cumsum(death)) %>%
  mutate(cumreleased = cumsum(released)) %>%
  mutate(date = as.Date(date, format="%m/%d/%Y"))

urlfile3= "https://raw.githubusercontent.com/Yunjeong-Kim/covid19_south_korea/master/daily_province.csv"
caseProvince <- read_csv(url(urlfile3))
colnames(caseProvince)[1:1] <- c("date")


caseProvince <- caseProvince %>%
  mutate(cumSeoul = cumsum(Seoul)) %>%
  mutate(cumDaegu = cumsum(Daegu)) %>%
  mutate(cumGyeonggi = cumsum(Gyeonggido)) %>%
  mutate(cumGyeongbuk = cumsum(Gyeongsangbukdo)) %>%
  mutate(date = as.Date(date, format="%m/%d/%Y"))

  
```


Column
-----------------------------------------------------------------------
### COVID-19 South Korea Map 
```{r}

urlfile4="https://raw.githubusercontent.com/Yunjeong-Kim/covid19_south_korea/master/daily_province_time_series.csv"
provinceMap <- read_csv(url(urlfile4))

total <- data.frame(rowSums(provinceMap[,-1:-3]))
sidoList <- data.frame(provinceMap[,1:3])
total <- cbind(total, sidoList)
newCol <- c("cumulative", "province", "lat", "lon")
colnames(total) <- newCol

library(leaflet)

total %>%
  leaflet() %>%
  addTiles() %>%
    addProviderTiles(provider = "CartoDB.Positron") %>%
    addCircleMarkers(
      stroke = FALSE, 
      label = ~cumulative, 
      radius = ~sqrt(cumulative),
      labelOptions = labelOptions(
        noHide = TRUE, 
        offset=c(0,-12),
        textOnly=TRUE, 
        style=list('color'='black', 'font-size'='15px')                                      ))
  

```

Row 
-----------------------------------------------------------------------

### Total Cases

```{r}
colors1 <- c("Daily Confirmed" = "#00AFBB", "Cumulative Confirmed" = "steelblue", "Cumulative Released" = "#E7B800")

plot1 <-ggplot(covid19, ) +
        geom_bar(aes(x=date, y=confirmed, fill = "Daily Confirmed"), stat = "identity") + 
        geom_line(aes(x=date, y=cumconfirmed, color = "Cumulative Confirmed"), stat="identity", size = 1.5) +
        geom_line(aes(x=date, y=cumreleased, color = "Cumulative Released"), stat="identity", size = 1.5) +
        labs(x="Date", y="Confirmed Cases", color="Legend") +
        scale_color_manual(values = colors1) +
        theme(axis.text.x=element_text(angle=45,hjust=1)) +
        theme_minimal()
plot1
ggplotly(plot1)
```

### Cases by City/Province

```{r}
colors2 <- c("Seoul"="steelblue", "Daegu"="#FC4E07", "Gyeonggi-do"="#00AFBB", "Gyeongsangbuk-do" = "#E7B800")

plot2 <- ggplot(caseProvince, ) +
        geom_line(aes(x=date, y=cumSeoul, color = "Seoul"), stat="identity", size = 1.5) +
        geom_line(aes(x=date, y=cumDaegu, color = "Daegu"), stat="identity", size = 1.5) +
        #geom_line(aes(x=date, y=cumGyeonggi, color = "Gyeonggi-do"), stat="identity", size = 1.5) +
        geom_line(aes(x=date, y=cumGyeongbuk, color = "Gyeongsangbuk-do"), stat="identity", size = 1.5) +
        labs(x="Date", y="Confirmed Cases", color="Legend") +
        scale_color_manual(values = colors2) +
        theme(axis.text.x=element_text(angle=45,hjust=1)) +
        theme_minimal()
plot2
ggplotly(plot2)
```
