---
title: "COVID19_SouthKorea"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    social: menu
    source_code: https://github.com/Yunjeong-Kim/covid19_south_korea
    theme: flatly
---

```{r setup, include=FALSE}
library(readr)
library(flexdashboard)
library(shiny)
library(leaflet)
library(dplyr)
library(RColorBrewer)
urlfile= "https://raw.githubusercontent.com/Yunjeong-Kim/covid19_south_korea/master/COVID19_screening_centers.csv"
korean <- read_csv(url(urlfile), locale = locale(date_names = "he", encoding = "UTF-8"))

#define sigungu
korean$sigungu <- as.factor(korean$sigungu)
korean$sido <- as.factor(korean$sido)
sigunguname <- levels(korean$sigungu)
sigunguname <- append(sigunguname, "All testing centers")
sidoname <- levels(korean$sido)
sidoname <- append(sidoname, "All testing centers")


```




Map
=======================================

input {.sidebar}
----------

<br>
<strong> Select your area </strong>
```{r}

# define inputs
selectInput("sido", label = "City or Province", choices = sidoname, selected ="All testing centers")
selectInput("sigungu", label = "County", choices = sigunguname)
```

<br>※ 호흡기 증상이나 코로나19 증상 의심시에는 먼저 관할 보건소 또는 1339콜센터 등의 상담을 받으신 후 선별진료소를 방문하십시오.<br><br>

※ If respiratory symptoms appear and you suspicious of COVID-19, please get the consultation from 1339 call center or public health center first then visit a COVID-19 screening center.<br><br>

※ 出现呼吸道症状或疑似感染新型冠状病毒肺炎时，请先向管辖区保健所或1339呼叫中心进行咨询后再前往指定诊疗机构.



output
----------
**COVID-19 Testing Centers**
```{r}

korean <- mutate(korean, centerinformation=paste0('<strong>Center Name: </strong>',centername,
                                          '<br><strong>Address:</strong> ', address,
                                          '<br><strong>Telephone:</strong> ', telephone
                                         )) 

filtereddata <- reactive({
                if (input$sido== "All testing centers"){
                        korean
                } else{
                        filter(korean, sido == input$sido)%>%
  filter(sigungu %in% input$sigungu)
                }
        })
observeEvent(input$sido,{
        updateSelectInput(
                session,"sigungu", choices = korean$sigungu[korean$sido == input$sido]
        )
})


 
# Draw the map that shows the testing center

pal <- colorFactor(c("#87CEEB", "#ff073a"), domain = c("O", "X"))

icons <- awesomeIcons(
  icon = 'hospital-o',  
  library = 'fa',
    iconColor = ~pal(screentest))

renderLeaflet({leaflet(filtereddata()) %>%
addProviderTiles('Esri.WorldStreetMap', group='Streets') %>%
  addProviderTiles('Esri.WorldImagery',group='Imagery') %>%
  addLayersControl(baseGroups=c('Streets','Imagery'),options = layersControlOptions(collapsed = F, autoZIndex =T)) %>% 
    addCircleMarkers(data= filtereddata(), lng= ~lon, lat= ~lat, color=~pal(screentest))  %>%
    addAwesomeMarkers(lng=~lon, lat=~lat, icon=icons, popup= ~centerinformation) %>% addLegend(pal=pal, values=~screentest, title="Covid-19 test", opacity=1, position="bottomright")
  })
 



```


Statistics
============================

```{r}
library(plotly)
library(ggplot2)
library(tidyverse)
urlfile2= "https://raw.githubusercontent.com/Yunjeong-Kim/covid19_south_korea/master/daily_total.csv"
dat <- read_csv(url(urlfile2))
covid19 <- data.frame(t(dat[-1]))
colnames(covid19)[1:5] <- c("test", "negative", "confirmed", "released", "death")
covid19<-tibble::rownames_to_column(covid19, "date") 
covid19 <- covid19 %>%
  mutate(cumconfirmed = cumsum(confirmed)) %>%
  mutate(cumdeath = cumsum(death)) %>%
  mutate(cumreleased = cumsum(released)) %>%
  mutate(date = as.Date(date, format="%m/%d/%Y"))
urlfile3= "https://raw.githubusercontent.com/Yunjeong-Kim/covid19_south_korea/master/daily_province.csv"
caseProvince <- read_csv(url(urlfile3))
colnames(caseProvince)[1:1] <- c("date")
caseProvince <- caseProvince %>%
  mutate(cumSeoul = cumsum(Seoul)) %>%
  mutate(cumDaegu = cumsum(Daegu)) %>%
  mutate(cumGyeonggi = cumsum(Gyeonggido)) %>%
  mutate(cumGyeongbuk = cumsum(Gyeongsangbukdo)) %>%
  mutate(date = as.Date(date, format="%m/%d/%Y"))
urlfile4="https://raw.githubusercontent.com/Yunjeong-Kim/covid19_south_korea/master/daily_province_time_series.csv"
provinceMap <- read_csv(url(urlfile4))
total <- data.frame(rowSums(provinceMap[,-1:-3]))
sidoList <- data.frame(provinceMap[,1:3])
total <- cbind(total, sidoList)
newCol <- c("cumulative", "province", "lat", "lon")
colnames(total) <- newCol
  
```
Column {.sidebar}
-----------------------------------------------------------------------
```{r}
confirmed <- as.numeric(apply(covid19[4], 2, sum))
death <- as.numeric(apply(covid19[6], 2, sum))
tested <- as.numeric(apply(covid19[2], 2, sum))
released <- as.numeric(apply(covid19[5], 2, sum))
city <- levels(as.factor(total$province))
inputPanel(
  h3('COVID-19 Status'),
  selectInput("city", label = "Select your city", choices = city, selected = "Daegu", width=200))
```
```{r}
output$confirmed <- renderPrint({confirmed})
output$death <- renderPrint({death})
output$deathrate <- renderPrint({death/confirmed})
output$tested <- renderPrint({tested})
output$released <- renderPrint({released})
```

#### Total Confirmed {.value-box}

```{r}
renderValueBox({
  valueBox(
    value = confirmed, 
    color = "#4682B4"
  )
})
```

#### Total Death {.value-box}
```{r}
renderValueBox({
  valueBox(
    value = death, 
    color = "#20B2AA"
  )
})
```

#### Total Tested {.value-box}
```{r}
renderValueBox({
  valueBox(
    value = tested, 
    color = "#20B2AA"
  )
})
```

#### Total Released {.value-box}
```{r}
renderValueBox({
  valueBox(
    value = released, 
    color = "#20B2AA"
  )
})
```



Column {data-width = 450}
-----------------------------------------------------------------------
### COVID-19 South Korea Map 

```{r}
library(leaflet)
total$province <- as.factor(total$province)
subDat <- reactive({
  total %>% 
    mutate(selected = 0)
  })
finalDat <- reactive({
  subDat() %>%
    mutate(selected = ifelse((length(input$city) > 0) & (province == noquote(input$city)), 1, 0))
})
pals <- colorFactor(c("#4169E1", "#DC143C"), domain = c(1, 0))
renderLeaflet({
  leaflet(finalDat()) %>%
    addProviderTiles(provider = "CartoDB.Positron") %>%
    addCircleMarkers(
      stroke = FALSE,
      lng = ~lon, lat = ~lat,
      label = ~cumulative, 
      radius = ~sqrt(cumulative),
      color = ~pals(selected),
      labelOptions = labelOptions(
        noHide = TRUE, 
        offset=c(0,-12),
        textOnly=TRUE, 
        style=list('color'='black', 'font-size'='15px')                                      ))
  
})
```


Column {data-width= 450}
-----------------------------------------------------------------------

### Daily Cases and Released

```{r}
colors1 <- c("Daily Confirmed" = "#4682B4", "Daily Released" = "#4682B4")
plot1 <-ggplot(covid19, ) +
        geom_bar(aes(x=date, y=confirmed, fill = "Daily Confirmed"), stat = "identity") + 
        geom_line(aes(x=date, y=released, color = "Daily Released"), stat="identity", size = 1.5) +
        labs(x="Date", y="Number", color="Legend") +
        scale_color_manual(values = colors1) +
        theme(axis.text.x=element_text(angle=45,hjust=1)) +
        theme_minimal()
plot1
ggplotly(plot1)
```

### Total Cases and Death

```{r}
colors2 <- c("Cumulative Confirmed" = "#4682B4", "Cumulative Death" = "#E7B800")
plot2 <-ggplot(covid19, ) +
        geom_line(aes(x=date, y=cumdeath, color = "Cumulative Death"), stat="identity", size = 1.5) +
        geom_line(aes(x=date, y=cumconfirmed, color = "Cumulative Confirmed"), stat="identity", size = 1.5) +
        labs(x="Date", y="Number", color="Legend") +
        scale_color_manual(values = colors2) +
        theme(axis.text.x=element_text(angle=45,hjust=1)) +
        theme_minimal()
plot2
ggplotly(plot2)
```

### Cases by City/Province

```{r}
colors3 <- c("Seoul"="steelblue", "Daegu"="#FC4E07", "Gyeonggi-do"="#00AFBB", "Gyeongsangbuk-do" = "#E7B800")
plot3 <- ggplot(caseProvince, ) +
  geom_line(aes(x=date, y=cumSeoul, color = "Seoul"), stat="identity", size = 1.5) +
  geom_line(aes(x=date, y=cumDaegu, color = "Daegu"), stat="identity", size = 1.5) +
  #geom_line(aes(x=date, y=cumGyeonggi, color = "Gyeonggi-do"), stat="identity", size = 1.5) +
  geom_line(aes(x=date, y=cumGyeongbuk, color = "Gyeongsangbuk-do"), stat="identity", size = 1.5) +
  labs(x="Date", y="Confirmed Cases", color="Legend") +
  scale_color_manual(values = colors3) +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  theme_minimal()
plot3
ggplotly(plot3)
```

